In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv("data/train.csv")
df.head(15)

,id,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f110,f111,f112,f113,f114,f115,f116,f117,f118,claim
0,0,0.108590,0.004314,-37.566,0.017364,0.289150,-10.251000,135.120,168900.0,3.992400e+14,...,-12.2280,1.7482,1.90960,-7.11570,4378.80,1.2096,8.613400e+14,140.10,1.017700,1
1,1,0.100900,0.299610,11822.000,0.276500,0.459700,-0.837330,1721.900,119810.0,3.874100e+15,...,-56.7580,4.1684,0.34808,4.14200,913.23,1.2464,7.575100e+15,1861.00,0.283590,0
2,2,0.178030,-0.006980,907.270,0.272140,0.459480,0.173270,2298.000,360650.0,1.224500e+13,...,-5.7688,1.2042,0.26290,8.13120,45119.00,1.1764,3.218100e+14,3838.20,0.406900,1
3,3,0.152360,0.007259,780.100,0.025179,0.519470,7.491400,112.510,259490.0,7.781400e+13,...,-34.8580,2.0694,0.79631,-16.33600,4952.40,1.1784,4.533000e+12,4889.10,0.514860,1
4,4,0.116230,0.502900,-109.150,0.297910,0.344900,-0.409320,2538.900,65332.0,1.907200e+15,...,-13.6410,1.5298,1.14640,-0.43124,3856.50,1.4830,-8.991300e+12,NaN,0.230490,1
5,5,0.101530,-0.002612,-1118.700,0.116300,0.318860,-0.478390,2372.800,-1808.0,5.818100e+15,...,-44.0820,3.5812,26.55900,-6.47220,44570.00,1.1776,2.997700e+14,5548.30,-0.033159,0
6,6,0.003073,0.359530,20913.000,0.003465,0.268060,-1.225100,1301.200,233180.0,1.771400e+15,...,-39.9220,1.4896,1.29230,33.63400,16201.00,1.2271,2.458900e+16,1012.90,0.647970,0
7,7,0.097340,0.245910,11775.000,0.614860,0.479370,-1.486500,3179.200,123940.0,1.652900e+15,...,-22.9950,1.5719,101.95000,1.51560,1117.50,1.2468,-6.971300e+13,1481.70,0.303170,1
8,8,-0.008948,0.338020,503.810,0.601520,0.261760,0.735380,1614.000,408030.0,7.684400e+14,...,-9.5142,2.2176,-1.23750,7.07130,1030.80,1.2040,5.290300e+15,1968.10,0.145930,0
9,9,0.126230,0.173960,1662.000,0.038081,0.000485,0.059909,296.070,-8035.3,4.526300e+15,...,-1.9684,3.9595,19.16900,-0.24498,838.39,1.1968,2.567000e+17,4914.90,0.519760,0
10,10,0.121570,0.275670,NaN,0.006199,0.473720,0.582000,2044.100,1117000.0,3.895900e+13,...,-43.1580,3.6750,7.97710,-20.50900,69084.00,1.3961,7.217100e+16,523.19,0.862240,1
11,11,0.078650,0.387450,1025.900,0.082626,0.267070,-1.476200,2170.100,513560.0,9.716600e+12,...,-17.1010,1.5954,121.02000,-9.33300,45667.00,1.2490,5.059300e+15,5422.30,0.570970,0
12,12,0.081278,0.302320,1341.000,0.516860,0.394170,-1.545600,105.600,1045900.0,-2.677900e+12,...,-1.7416,1.7956,-0.84064,-8.44710,6079.10,1.1926,1.759800e+16,6521.70,0.951500,1
13,13,0.071683,0.341330,342.300,-0.003108,0.004038,-1.058900,1126.500,126430.0,5.915300e+12,...,-2.9630,1.1850,103.17000,30.20300,151650.00,1.2005,5.740900e+15,5203.90,0.688690,1
14,14,0.072488,0.473410,-22.274,0.002846,0.384460,3.548400,-40.267,739910.0,4.615400e+15,...,-10.3290,1.6152,195.36000,1.05310,1806.40,1.2229,6.537300e+15,591.48,0.300380,1

In [30]:
df.isna().sum()

id           0
f1       15247
f2       15190
f3       15491
f4       15560
         ...
f115     15559
f116     15589
f117     15407
f118     15212
claim        0
Length: 120, dtype: int64

In [31]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 957919 entries, 0 to 957918
Columns: 120 entries, id to claim
dtypes: float64(118), int64(2)
memory usage: 877.0 MB

,id,f1,f2,f3,f4,f5,f6,f7,f8,f9,...,f110,f111,f112,f113,f114,f115,f116,f117,f118,claim
count,957919.000000,942672.000000,942729.000000,942428.000000,942359.000000,942514.000000,942398.000000,942415.000000,9.425460e+05,9.426700e+05,...,942554.000000,942420.000000,942509.000000,942686.000000,942481.000000,942360.000000,9.423300e+05,942512.000000,942707.000000,957919.000000
mean,478959.000000,0.090201,0.345964,4068.744207,0.201214,0.304869,-0.071458,1620.843815,3.771642e+05,1.806054e+15,...,-19.926398,2.074530,23.885245,1.748777,63152.973540,1.208876,4.276905e+16,3959.204669,0.559267,0.498492
std,276527.540593,0.043564,0.146251,6415.829440,0.212510,0.145343,2.123777,1276.281403,3.454325e+05,2.335204e+15,...,18.578439,0.895793,45.581360,10.088848,92435.016241,0.114959,6.732441e+16,3155.991777,0.408426,0.499998
min,0.000000,-0.149910,-0.019044,-9421.700000,-0.082122,-0.006990,-12.791000,-224.800000,-2.984300e+04,-1.153300e+15,...,-105.860000,0.277040,-27.691000,-26.589000,-81977.000000,0.905270,-8.944400e+15,-415.240000,-0.151240,0.000000
25%,239479.500000,0.070227,0.283050,418.430000,0.035086,0.240520,-1.120700,481.545000,9.120900e+04,1.153100e+13,...,-28.812000,1.487700,-0.628880,-4.473975,2443.200000,1.146800,2.321100e+14,1306.200000,0.276560,0.000000
50%,478959.000000,0.090135,0.389100,1279.500000,0.137000,0.327790,-0.380110,1446.100000,2.896700e+05,5.043050e+14,...,-14.636000,1.662100,1.727700,0.885710,19479.000000,1.177200,1.327500e+16,3228.000000,0.473440,0.000000
75%,718438.500000,0.116500,0.458450,4444.400000,0.297100,0.412830,0.921940,2495.900000,5.605600e+05,3.103100e+15,...,-5.325300,2.522325,18.991000,6.840775,88488.000000,1.242000,5.278700e+16,6137.900000,0.746210,1.000000
max,957918.000000,0.415170,0.518990,39544.000000,1.319900,0.554750,11.202000,5426.600000,1.913700e+06,1.042400e+16,...,1.613400,4.565900,217.840000,47.757000,526050.000000,1.886700,3.249900e+17,13151.000000,2.743600,1.000000

In [32]:
def preprocessing(data):
    data = data.drop(['id'], axis=1)

    # data['f40_sqr'] = data['f40'] ** 2
    # data['f40_f70'] = data['f40'] * data['f70']

    data["row_std"] = data.std(axis=1)
    data["row_min"] = data.min(axis=1)
    # data["row_max"] = data.max(axis=1)
    # data["row_mean"] = data.mean(axis=1)
    data["row_sum"] = data.isna().sum(axis=1)

    return data

In [33]:
from sklearn.model_selection import train_test_split


X = df.copy()
X = preprocessing(X)

y = X.pop('claim')

X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=0
    )

X_train.head()

,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,...,f112,f113,f114,f115,f116,f117,f118,row_std,row_min,row_sum
849769,0.081263,-0.015084,425.46,0.917050,0.26711,1.59620,3961.600,25498.0,6.747500e+15,1326.400,...,15.9630,8.3114,105760.00,1.3356,5.460900e+16,5252.000,1.445800,5.051337e+15,-1.806200e+04,0
496677,0.154330,0.439760,1003.50,0.203640,0.19866,-0.96090,22.824,123170.0,1.540000e+13,12.629,...,103.4500,6.1921,7063.90,1.1936,2.365800e+16,1053.000,-0.037614,2.222520e+15,-6.398700e+10,1
423894,0.090109,0.226640,3293.10,0.022147,0.15728,-0.70278,599.080,365050.0,1.494400e+14,4747.900,...,-2.8700,-4.5644,14207.00,1.2402,7.898600e+15,-10.104,0.383630,8.396487e+14,-1.168900e+03,0
310822,0.118320,0.502870,18165.00,0.281700,0.29825,-0.60408,1671.900,569390.0,5.128700e+15,33739.000,...,1.8177,-1.0232,182330.00,1.1557,1.668000e+14,2694.700,0.244380,4.742415e+14,-1.151100e+12,2
658037,0.003837,0.253780,2018.30,0.045150,0.24189,-1.68080,3749.600,262840.0,6.426100e+14,1209.700,...,7.1085,6.1064,-359.86,1.2408,3.026700e+16,1913.400,1.473300,2.810310e+15,-2.373800e+10,3

In [34]:
from lightgbm import LGBMClassifier


model = LGBMClassifier(
    n_estimators=1000,
    random_state=0,
    learning_rate=0.05,
    num_leaves=64,
)
model.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 382073, number of negative: 384262
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.184764 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 30600
[LightGBM] [Info] Number of data points in the train set: 766335, number of used features: 121
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.498572 -> initscore=-0.005713
[LightGBM] [Info] Start training from score -0.005713

LGBMClassifier(learning_rate=0.05, n_estimators=1000, num_leaves=64,
               random_state=0)

In [35]:
from sklearn.metrics import roc_auc_score


predict = model.predict_proba(X_valid)[:, 1]

features = model.feature_importances_
feature_names = X_train.columns

feat_importances = pd.Series(features, index=feature_names)
display(feat_importances.nlargest(20))


print(f"Accuracy: {roc_auc_score(y_valid, predict)}")

f40     862
f70     799
f47     752
f34     686
f1      668
f35     661
f107    652
f79     644
f45     640
f57     640
f65     637
f5      636
f21     631
f77     630
f8      629
f3      617
f106    606
f95     602
f96     595
f62     591
dtype: int32

Accuracy: 0.8135728074973076

In [36]:
test_df = pd.read_csv('data/test.csv')

test_X_df = preprocessing(test_df)

preds = model.predict_proba(test_X_df)[:, 1]

submission = pd.DataFrame({
    "id": test_df['id'],
    "claim": preds
})

submission.to_csv('submission.csv', index=False)

C:\Users\Windows11\AppData\Local\Temp\ipykernel_17208\1823016355.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["row_std"] = data.std(axis=1)
C:\Users\Windows11\AppData\Local\Temp\ipykernel_17208\1823016355.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["row_min"] = data.min(axis=1)
C:\Users\Windows11\AppData\Local\Temp\ipykernel_17208\1823016355.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["row_sum"] = data.isna().sum(axis=1)